on:
    workflow_dispatch:
    pull_request:
      branches: [ main ] # target branch!
      types: [ closed, opened, synchronize, reopened ]
    issue_comment:
      types: [created]

jobs:
    run-digger:
      runs-on: zon-ubuntu-general-dind

      permissions:
        contents: write      # required to merge PRs
        id-token: write      # required for workload-identity-federation
        pull-requests: write # required to post PR comments
        statuses: write      # required to validate combined PR status

      steps:

        - name: Vault OIDC Auth
          uses: hashicorp/vault-action@v2.8.0
          id: vault
          with:
            url: ${{ secrets.VAULT_ADDR }}
            method: jwt
            path: github-actions
            role: terraform-ops
            exportToken: true
            secrets: zon/v1/github/atlantis gh_token

        - name: Write gitconfig
          run: git config --global url."https://oauth2:${{ steps.vault.outputs.gh_token }}@github.com".insteadOf ssh://git@github.com # replace ssh auth with https token auth for private terraform-module repo

        - name: digger run
          uses: diggerhq/digger@v0.4.9
          with:
            digger-token: ${{ secrets.DIGGER_TOKEN_DEVEL }}
            digger-organisation: "Zeit Online"
            digger-hostname: "https://digger.devel.zon.zeit.de"
            # digger-hostname: 'https://cloud.digger.dev'
            setup-google-cloud: true #needed, or auth step is skipped
            google-workload-identity-provider: ${{ vars.GHA_WIF_PROVIDER }}
            google-service-account: gha-terraform@zeitonline-engineering.iam.gserviceaccount.com
            # google-workload-identity-provider-audience: google-wif
            disable-locking: true
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEBUG: 'true'
            VAULT_ADDR: https://vault.ops.zeit.de
            # LOCK_PROVIDER: gcp
